"""
Email service for sending PDFs via SendGrid.
Handles email delivery with PDF attachments.
"""

import base64
import logging
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName, FileType, Disposition

logger = logging.getLogger(__name__)


class EmailService:
    """Service for sending emails via SendGrid."""

    def __init__(self, api_key: str, from_email: str = "noreply@casebase.com"):
        """
        Initialize the email service.

        Args:
            api_key: SendGrid API key
            from_email: Email address to send from
        """
        self.api_key = api_key
        self.from_email = from_email
        self.client = SendGridAPIClient(api_key)

    async def send_pdf_email(
        self,
        to_email: str,
        subject: str,
        pdf_bytes: bytes,
        pdf_filename: str,
        message_body: str = None
    ) -> dict:
        """
        Send an email with a PDF attachment.

        Args:
            to_email: Recipient email address
            subject: Email subject line
            pdf_bytes: PDF file content as bytes
            pdf_filename: Name for the PDF attachment
            message_body: Optional custom message body

        Returns:
            dict: Response from SendGrid API

        Raises:
            Exception: If email sending fails
        """
        try:
            # Default message body if none provided
            if not message_body:
                message_body = f"""
                <html>
                <body>
                    <h2>Your CaseBase PDF Document</h2>
                    <p>Hello,</p>
                    <p>Your requested PDF document is attached to this email.</p>
                    <p>This document was generated by CaseBase AI Assistant.</p>
                    <br>
                    <p>Best regards,<br>
                    <strong>Casey - CaseBase AI Assistant</strong></p>
                    <hr>
                    <p style="font-size: 12px; color: #666;">
                        This is an automated email from CaseBase. Please do not reply to this message.
                    </p>
                </body>
                </html>
                """

            # Create the email message
            message = Mail(
                from_email=self.from_email,
                to_emails=to_email,
                subject=subject,
                html_content=message_body
            )

            # Encode PDF to base64
            encoded_pdf = base64.b64encode(pdf_bytes).decode()

            # Create attachment
            attachment = Attachment(
                FileContent(encoded_pdf),
                FileName(pdf_filename),
                FileType('application/pdf'),
                Disposition('attachment')
            )

            message.attachment = attachment

            # Send email
            logger.info(f"Sending PDF email to {to_email}")
            response = self.client.send(message)

            logger.info(f"Email sent successfully. Status code: {response.status_code}")

            return {
                "success": True,
                "status_code": response.status_code,
                "message": f"PDF successfully sent to {to_email}"
            }

        except Exception as e:
            logger.error(f"Failed to send email: {str(e)}")
            raise Exception(f"Email delivery failed: {str(e)}")


# Global email service instance (will be initialized in main.py)
email_service = None
