"""
Email service for sending PDFs via SendGrid.
Handles email delivery with PDF attachments.
"""

import base64
import logging
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName, FileType, Disposition

logger = logging.getLogger(__name__)


class EmailService:
    """Service for sending emails via SendGrid."""

    def __init__(self, api_key: str, from_email: str = "noreply@casebase.com"):
        """
        Initialize the email service.

        Args:
            api_key: SendGrid API key
            from_email: Email address to send from
        """
        self.api_key = api_key
        self.from_email = from_email
        self.client = SendGridAPIClient(api_key)

    async def send_pdf_email(
        self,
        to_email: str,
        subject: str,
        pdf_bytes: bytes,
        pdf_filename: str,
        message_body: str = None
    ) -> dict:
        """
        Send an email with a PDF attachment.

        Args:
            to_email: Recipient email address
            subject: Email subject line
            pdf_bytes: PDF file content as bytes
            pdf_filename: Name for the PDF attachment
            message_body: Optional custom message body

        Returns:
            dict: Response from SendGrid API

        Raises:
            Exception: If email sending fails
        """
        try:
            # Default message body if none provided
            if not message_body:
                message_body = f"""
                <html>
                <body>
                    <h2>Your CaseBase PDF Document</h2>
                    <p>Hello,</p>
                    <p>Your requested PDF document is attached to this email.</p>
                    <p>This document was generated by CaseBase AI Assistant.</p>
                    <br>
                    <p>Best regards,<br>
                    <strong>Casey - CaseBase AI Assistant</strong></p>
                    <hr>
                    <p style="font-size: 12px; color: #666;">
                        This is an automated email from CaseBase. Please do not reply to this message.
                    </p>
                </body>
                </html>
                """

            # Create the email message
            message = Mail(
                from_email=self.from_email,
                to_emails=to_email,
                subject=subject,
                html_content=message_body
            )

            # Encode PDF to base64
            encoded_pdf = base64.b64encode(pdf_bytes).decode()

            # Create attachment
            attachment = Attachment(
                FileContent(encoded_pdf),
                FileName(pdf_filename),
                FileType('application/pdf'),
                Disposition('attachment')
            )

            message.attachment = attachment

            # Send email
            logger.info(f"Sending PDF email to {to_email}")
            response = self.client.send(message)

            logger.info(f"Email sent successfully. Status code: {response.status_code}")

            return {
                "success": True,
                "status_code": response.status_code,
                "message": f"PDF successfully sent to {to_email}"
            }

        except Exception as e:
            logger.error(f"Failed to send email: {str(e)}")
            raise Exception(f"Email delivery failed: {str(e)}")

    async def send_pdf_email_with_sources(
        self,
        to_email: str,
        subject: str,
        main_pdf_bytes: bytes,
        main_pdf_filename: str,
        source_pdfs: list = None,
        message_body: str = None
    ) -> dict:
        """
        Send an email with multiple PDF attachments (main PDF + source documents).

        Args:
            to_email: Recipient email address
            subject: Email subject line
            main_pdf_bytes: Main/generated PDF file content as bytes
            main_pdf_filename: Name for the main PDF attachment
            source_pdfs: List of dicts with 'bytes' and 'filename' keys for source PDFs
            message_body: Optional custom message body

        Returns:
            dict: Response from SendGrid API

        Raises:
            Exception: If email sending fails
        """
        try:
            # Default message body if none provided
            if not message_body:
                source_count = len(source_pdfs) if source_pdfs else 0
                source_text = f"<p>Also included: {source_count} supporting document(s) used to generate this report.</p>" if source_count > 0 else ""

                message_body = f"""
                <html>
                <body>
                    <h2>Your CaseBase PDF Document</h2>
                    <p>Hello,</p>
                    <p>Your requested PDF document is attached to this email.</p>
                    {source_text}
                    <p>This document was generated by CaseBase AI Assistant.</p>
                    <br>
                    <p>Best regards,<br>
                    <strong>Casey - CaseBase AI Assistant</strong></p>
                    <hr>
                    <p style="font-size: 12px; color: #666;">
                        This is an automated email from CaseBase. Please do not reply to this message.
                    </p>
                </body>
                </html>
                """

            # Create the email message
            message = Mail(
                from_email=self.from_email,
                to_emails=to_email,
                subject=subject,
                html_content=message_body
            )

            # Attach main PDF
            encoded_main_pdf = base64.b64encode(main_pdf_bytes).decode()
            main_attachment = Attachment(
                FileContent(encoded_main_pdf),
                FileName(main_pdf_filename),
                FileType('application/pdf'),
                Disposition('attachment')
            )
            message.add_attachment(main_attachment)

            # Attach source PDFs if provided
            if source_pdfs:
                for idx, source_pdf in enumerate(source_pdfs):
                    encoded_source = base64.b64encode(source_pdf['bytes']).decode()
                    source_attachment = Attachment(
                        FileContent(encoded_source),
                        FileName(source_pdf['filename']),
                        FileType('application/pdf'),
                        Disposition('attachment')
                    )
                    message.add_attachment(source_attachment)
                    logger.info(f"Added source PDF attachment {idx + 1}: {source_pdf['filename']}")

            # Send email
            attachment_count = 1 + (len(source_pdfs) if source_pdfs else 0)
            logger.info(f"Sending email to {to_email} with {attachment_count} PDF attachment(s)")
            response = self.client.send(message)

            logger.info(f"Email sent successfully. Status code: {response.status_code}")

            return {
                "success": True,
                "status_code": response.status_code,
                "message": f"PDF successfully sent to {to_email} with {attachment_count} attachment(s)"
            }

        except Exception as e:
            logger.error(f"Failed to send email with sources: {str(e)}")
            raise Exception(f"Email delivery failed: {str(e)}")

    async def send_documents_email(
        self,
        to_email: str,
        subject: str,
        documents: list,
        message_body: str = None
    ) -> dict:
        """
        Send an email with multiple document attachments (no main PDF).

        Args:
            to_email: Recipient email address
            subject: Email subject line
            documents: List of dicts with 'bytes' and 'filename' keys for documents
            message_body: Optional custom message body

        Returns:
            dict: Response from SendGrid API

        Raises:
            Exception: If email sending fails
        """
        try:
            # Default message body if none provided
            if not message_body:
                doc_count = len(documents) if documents else 0
                message_body = f"""
                <html>
                <body>
                    <h2>Your Requested Documents</h2>
                    <p>Hello,</p>
                    <p>Here are the {doc_count} document(s) you requested.</p>
                    <p>All files are attached to this email.</p>
                    <br>
                    <p>Best regards,<br>
                    <strong>Casey - CaseBase AI Assistant</strong></p>
                    <hr>
                    <p style="font-size: 12px; color: #666;">
                        This is an automated email from CaseBase. Please do not reply to this message.
                    </p>
                </body>
                </html>
                """

            # Create the email message
            message = Mail(
                from_email=self.from_email,
                to_emails=to_email,
                subject=subject,
                html_content=message_body
            )

            # Attach all documents
            if documents:
                for idx, doc in enumerate(documents):
                    encoded_doc = base64.b64encode(doc['bytes']).decode()
                    attachment = Attachment(
                        FileContent(encoded_doc),
                        FileName(doc['filename']),
                        FileType('application/pdf'),
                        Disposition('attachment')
                    )
                    message.add_attachment(attachment)
                    logger.info(f"Added document attachment {idx + 1}: {doc['filename']}")

            # Send email
            attachment_count = len(documents) if documents else 0
            logger.info(f"Sending email to {to_email} with {attachment_count} document attachment(s)")
            response = self.client.send(message)

            logger.info(f"Email sent successfully. Status code: {response.status_code}")

            return {
                "success": True,
                "status_code": response.status_code,
                "message": f"Documents successfully sent to {to_email} ({attachment_count} attachment(s))"
            }

        except Exception as e:
            logger.error(f"Failed to send documents email: {str(e)}")
            raise Exception(f"Email delivery failed: {str(e)}")


# Global email service instance (will be initialized in main.py)
email_service = None
